openapi: 3.0.0
info:
  title: 'API Layanan KP'
  description: 'Dokumentasi API Validasi Logbook Mahasiswa, Pembimbingan, dan Surat Tugas.'
  contact:
    email: admin@unand.ac.id
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Laravel Dev Server

paths:
  # Logbook (Siswa) - POST (Store)
  /api/logbook:
    post:
      tags:
        - 'Logbook (Siswa)'
      summary: 'Siswa mengunggah Logbook kegiatan mingguan (termasuk file).'
      description: 'Mengunggah Logbook baru. Mendukung pengiriman file kegiatan opsional.'
      operationId: storeLogbook
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - student_id
                - minggu_ke
                - tanggal_mulai
                - deskripsi_kegiatan
              properties:
                student_id:
                  description: 'ID Siswa'
                  type: integer
                  example: 5
                minggu_ke:
                  description: 'Minggu ke- KP (unik per siswa)'
                  type: integer
                  example: 3
                tanggal_mulai:
                  description: 'Tanggal mulai minggu kegiatan (YYYY-MM-DD)'
                  type: string
                  format: date
                  example: '2025-01-20'
                deskripsi_kegiatan:
                  type: string
                  example: 'Melakukan instalasi dan konfigurasi server.'
                file_kegiatan:
                  description: 'File pendukung (maks 2MB, pdf, doc, docx, jpg, jpeg, png).'
                  type: string
                  format: binary
                  nullable: true
      responses:
        '201':
          description: 'Logbook berhasil dibuat.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogbookKP'
        '422':
          description: 'Kesalahan Validasi.'

  # Logbook (Siswa) - GET All by Student ID
  /api/logbook/{studentId}:
    get:
      tags:
        - 'Logbook (Siswa)'
      summary: 'Mengambil semua Logbook (beserta validasinya) untuk seorang siswa.'
      description: 'Menampilkan daftar semua Logbook siswa untuk pelacakan kemajuan KP.'
      operationId: indexLogbook
      parameters:
        - name: studentId
          in: path
          description: 'ID Siswa'
          required: true
          schema:
            type: integer
            format: int64
            example: 5
      responses:
        '200':
          description: 'Daftar Logbook siswa.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LogbookKPWithValidation'

  # Logbook (Siswa) - GET Detail by Logbook ID
  /api/logbook/detail/{logbookId}:
    get:
      tags:
        - 'Logbook (Siswa)'
      summary: 'Menampilkan detail satu Logbook.'
      description: 'Mendapatkan detail Logbook beserta data validasinya.'
      operationId: showLogbook
      parameters:
        - name: logbookId
          in: path
          description: 'ID Logbook'
          required: true
          schema:
            type: integer
            format: int64
            example: 10
      responses:
        '200':
          description: 'Detail Logbook.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogbookKPWithValidation'
        '404':
          description: 'Logbook tidak ditemukan.'

  # Logbook (Siswa) - PUT/DELETE (Update/Destroy)
  /api/logbook/{logbookId}:
    post:
      tags:
        - 'Logbook (Siswa)'
      summary: 'Siswa mengupdate Logbook yang belum divalidasi'
      description: "Memperbarui data Logbook KP. Pembaruan hanya dapat dilakukan jika status Logbook masih 'Pending'. File kegiatan dapat diganti (opsional)."
      operationId: updateLogbook
      parameters:
        -
          name: logbookId
          in: path
          description: 'ID Logbook'
          required: true
          schema:
            type: integer
            example: 10
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              required:
                - minggu_ke
                - tanggal_mulai
                - deskripsi_kegiatan
              properties:
                minggu_ke:
                  description: 'Minggu ke kegiatan KP'
                  type: integer
                  example: 4
                tanggal_mulai:
                  type: string
                  format: date
                  example: '2025-01-27'
                deskripsi_kegiatan:
                  type: string
                  example: 'Melakukan coding modul A.'
                file_kegiatan:
                  description: 'File laporan/kegiatan (pdf, doc, docx, jpg, png) — opsional'
                  type: string
                  format: binary
              type: object
      responses:
        200:
          description: 'Logbook berhasil diperbarui'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogbookKP'
        403:
          description: 'Logbook sudah divalidasi dan tidak dapat diubah'
        404:
          description: 'Logbook tidak ditemukan'
        422:
          description: 'Kesalahan validasi'
    delete:
      tags:
        - 'Logbook (Siswa)'
      summary: 'Siswa menghapus Logbook yang belum divalidasi.'
      description: "Menghapus data Logbook. Penghapusan diblokir jika status Logbook bukan 'Pending'."
      operationId: destroyLogbook
      parameters:
        - name: logbookId
          in: path
          description: 'ID Logbook'
          required: true
          schema:
            type: integer
            format: int64
            example: 10
      responses:
        '200':
          description: 'Logbook berhasil dihapus.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Logbook berhasil dihapus.'
        '403':
          description: 'Logbook sudah divalidasi dan tidak dapat dihapus.'
        '404':
          description: 'Logbook tidak ditemukan.'

  # --- Validasi Logbook Endpoints ---
  /api/validasi-logbook:
    get:
      tags:
        - 'Validasi Logbook'
      summary: 'Menampilkan semua data validasi'
      operationId: getAllValidasiLogbook
      responses:
        '200':
          description: Success
    post:
      tags:
        - 'Validasi Logbook'
      summary: 'Membuat validasi baru'
      operationId: createValidasiLogbook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - logbook_kp_id
                - lecturer_id
                - status_validasi
              properties:
                logbook_kp_id:
                  type: integer
                  example: 1
                  description: 'ID Logbook Kerja Praktik yang divalidasi.'
                lecturer_id:
                  type: integer
                  example: 12
                  description: 'ID Dosen yang melakukan validasi.'
                status_validasi:
                  type: string
                  example: Disetujui
                  description: 'Status validasi (misal: Disetujui, Revisi, Ditolak).'
                catatan_pembimbing:
                  type: string
                  example: 'Bagus, lanjutkan.'
                  description: 'Catatan tambahan dari dosen pembimbing (opsional).'
      responses:
        '201':
          description: 'Validasi berhasil dibuat'
        '422':
          description: 'Validasi gagal (misal: data input tidak valid)'

  /api/validasi-logbook/{id}:
    parameters:
      - name: id
        in: path
        description: 'ID Validasi Logbook'
        required: true
        schema:
          type: integer
          format: int64
          example: 1
    get:
      tags:
        - 'Validasi Logbook'
      summary: 'Menampilkan detail validasi berdasarkan ID'
      operationId: getValidasiLogbookById
      responses:
        '200':
          description: Success
        '404':
          description: 'Not Found'
    put:
      tags:
        - 'Validasi Logbook'
      summary: 'Memperbarui validasi logbook'
      operationId: updateValidasiLogbook
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status_validasi:
                  type: string
                  example: Revisi
                  description: 'Status validasi yang baru.'
                catatan_pembimbing:
                  type: string
                  example: 'Tolong revisi bagian hasil.'
                  description: 'Catatan pembimbing yang diperbarui.'
      responses:
        '200':
          description: Updated
        '404':
          description: 'Not Found'
    delete:
      tags:
        - 'Validasi Logbook'
      summary: 'Menghapus validasi logbook'
      operationId: deleteValidasiLogbook
      responses:
        '200':
          description: Deleted
        '404':
          description: 'Not Found'

  # --- Pembimbingan Endpoints ---
  /api/tentukan-pembimbing:
    post:
      tags:
        - Pembimbingan
      summary: 'Menentukan dosen pembimbing baru.'
      description: 'Mencatat penunjukan dosen pembimbing beserta judul tugas untuk mahasiswa.'
      operationId: tentukanPembimbing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - student_id
                - lecturer_id
                - judul
              properties:
                student_id:
                  description: 'ID Mahasiswa yang akan dibimbing.'
                  type: integer
                  example: 1
                lecturer_id:
                  description: 'ID Dosen pembimbing.'
                  type: integer
                  example: 12
                judul:
                  description: 'Judul tugas yang akan dibimbing.'
                  type: string
                  example: 'Rancangan Sistem Informasi Akademik'
      responses:
        '201':
          description: 'Dosen pembimbing berhasil ditentukan'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Dosen pembimbing berhasil ditentukan'
        '422':
          description: 'Validasi gagal'

  /api/update-pembimbing/{id}:
    parameters:
      - name: id
        in: path
        description: 'ID data Supervision (pembimbingan)'
        required: true
        schema:
          type: integer
          format: int64
          example: 1
    put:
      tags:
        - Pembimbingan
      summary: 'Memperbarui dosen pembimbing dan/atau judul tugas.'
      description: 'Memperbarui data pembimbing (Supervision), menghapus surat tugas lama, dan membuat yang baru secara otomatis.'
      operationId: updatePembimbing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - lecturer_id
              properties:
                lecturer_id:
                  description: 'ID Dosen pembimbing yang baru.'
                  type: integer
                  example: 15
                judul:
                  description: 'Judul tugas yang diperbarui (optional).'
                  type: string
                  example: 'Perancangan Ulang Sistem Informasi'
      responses:
        '200':
          description: 'Dosen pembimbing berhasil diperbarui dan surat tugas baru dibuat'
        '404':
          description: 'Data pembimbing tidak ditemukan'

  /api/kirim-notifikasi/{supervisionId}:
    post:
      tags:
        - Pembimbingan
      summary: 'Mengirim notifikasi penunjukan pembimbing.'
      description: 'Mensimulasikan pengiriman notifikasi/email ke mahasiswa dan dosen terkait penunjukan.'
      operationId: kirimNotifikasi
      parameters:
        - name: supervisionId
          in: path
          description: 'ID data Supervision yang akan dikirimkan notifikasi.'
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: 'Notifikasi berhasil dikirim ke mahasiswa dan dosen'
        '404':
          description: 'Data pembimbing tidak ditemukan'

  # --- Surat Tugas Endpoints ---
  /api/buat-surat-tugas:
    post:
      tags:
        - 'Surat Tugas'
      summary: 'Membuat dan menyimpan surat tugas pembimbing.'
      description: 'Membuat file surat tugas (simulasi .txt) dan mencatatnya ke database.'
      operationId: buatSuratTugas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - supervision_id
              properties:
                supervision_id:
                  description: 'ID data Supervision yang akan dibuatkan surat tugas.'
                  type: integer
                  example: 1
      responses:
        '201':
          description: 'Surat tugas pembimbing berhasil dibuat'
        '404':
          description: 'Data pembimbing tidak ditemukan'

  # --- JALUR UNTUK MENGUNDUH (GET) ---
  /api/download-surat-tugas/{id}:
    parameters:
      - name: id
        in: path
        description: 'ID SuratTugas'
        required: true
        schema:
          type: integer
          format: int64
          example: 1
    get:
      tags:
        - 'Surat Tugas'
      summary: 'Mengunduh file surat tugas.'
      description: 'Mengunduh file surat tugas yang tersimpan di storage lokal berdasarkan ID Surat Tugas.'
      operationId: download-surat-tuga
      responses:
        '200':
          description: 'Berhasil mengunduh file.'
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: 'File surat tugas tidak ditemukan'

  # --- JALUR KHUSUS UNTUK MENGHAPUS (DELETE) ---
  /api/delete-surat-tugas/{id}:
    parameters:
      - name: id
        in: path
        description: 'ID SuratTugas yang akan dihapus.'
        required: true
        schema:
          type: integer
          format: int64
          example: 1
    delete:
      tags:
        - 'Surat Tugas'
      summary: 'Menghapus surat tugas dan file terkait.'
      description: 'Menghapus record SuratTugas dari database dan file dari storage.'
      operationId: deleteSuratTugas
      responses:
        '200':
          description: 'Surat tugas pembimbing berhasil dihapus'
        '404':
          description: 'Surat tugas pembimbing tidak ditemukan'

tags:
  - name: 'Logbook (Siswa)'
    description: 'Operasi CRUD dan Tracking Logbook kegiatan KP oleh Mahasiswa.'
  - name: 'Validasi Logbook'
    description: 'API untuk melakukan validasi logbook mahasiswa'
  - name: Pembimbingan
    description: 'API untuk penentuan, pembaruan, dan notifikasi dosen pembimbing'
  - name: 'Surat Tugas'
    description: 'API untuk pembuatan dan pengelolaan surat tugas pembimbing'

# --- KOMPONEN SKEMA (SCHEMAS) UNTUK REFERENSI YANG HILANG ---
components:
  schemas:
    # 1. Skema LogbookKP (Model Dasar Logbook)
    LogbookKP:
      type: object
      properties:
        id:
          type: integer
          description: ID unik Logbook.
          example: 10
        student_id:
          type: integer
          example: 5
        minggu_ke:
          type: integer
          example: 3
        tanggal_mulai:
          type: string
          format: date
          example: '2025-01-20'
        deskripsi_kegiatan:
          type: string
          example: 'Melakukan instalasi dan konfigurasi server.'
        file_kegiatan_url:
          type: string
          nullable: true
          description: URL ke file yang diunggah.
          example: '/storage/logbook/5/week_3_file.pdf'
        status_logbook:
          type: string
          description: Status terakhir logbook (Pending, Disetujui, Revisi).
          example: Pending
        created_at:
          type: string
          format: date-time
          example: '2025-01-22T08:00:00Z'
        updated_at:
          type: string
          format: date-time
          example: '2025-01-22T08:00:00Z'

    # 2. Skema ValidasiDetail (Model Detail Validasi oleh Dosen)
    ValidasiDetail:
      type: object
      properties:
        id:
          type: integer
          description: ID unik Validasi.
          example: 1
        logbook_kp_id:
          type: integer
          description: ID Logbook yang divalidasi.
          example: 10
        lecturer_id:
          type: integer
          description: ID Dosen yang melakukan validasi.
          example: 12
        status_validasi:
          type: string
          description: Status validasi (Disetujui, Revisi, Ditolak).
          example: Disetujui
        catatan_pembimbing:
          type: string
          nullable: true
          description: Catatan tambahan dari dosen.
          example: 'Bagus, lanjutkan.'
        tanggal_validasi:
          type: string
          format: date-time
          example: '2025-01-28T10:00:00Z'
          
    # 3. Skema LogbookKPWithValidation (Model Logbook + Validasi)
    LogbookKPWithValidation:
      allOf:
        - $ref: '#/components/schemas/LogbookKP' # Mewarisi semua properti LogbookKP
        - type: object
          properties:
            validasi:
              type: array
              description: Daftar riwayat validasi yang diterima untuk logbook ini.
              items:
                $ref: '#/components/schemas/ValidasiDetail'