openapi: 3.0.0
info:
  title: 'API Layanan KP'
  description: 'Dokumentasi API Validasi Logbook Mahasiswa, Pembimbingan, dan Surat Tugas.'
  contact:
    email: admin@unand.ac.id
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Laravel Dev Server
    
paths:
  /pembimbing:
    post:
      tags:
        - Pembimbingan
      summary: 'Menentukan dosen pembimbing baru.'
      description: 'Mencatat penunjukan dosen pembimbing beserta judul tugas untuk mahasiswa.'
      operationId: tentukanPembimbing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - student_id
                - lecturer_id
                - judul
              properties:
                student_id:
                  description: 'ID Mahasiswa yang akan dibimbing.'
                  type: integer
                  example: 1
                lecturer_id:
                  description: 'ID Dosen pembimbing.'
                  type: integer
                  example: 12
                judul:
                  description: 'Judul tugas yang akan dibimbing.'
                  type: string
                  example: 'Rancangan Sistem Informasi Akademik'
      responses:
        '201':
          description: 'Dosen pembimbing berhasil ditentukan'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Dosen pembimbing berhasil ditentukan'
        '422':
          description: 'Validasi gagal'
          
  /surat-tugas:
    post:
      tags:
        - 'Surat Tugas'
      summary: 'Membuat dan menyimpan surat tugas pembimbing.'
      description: 'Membuat file surat tugas (simulasi .txt) dan mencatatnya ke database.'
      operationId: buatSuratTugas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - supervision_id
              properties:
                supervision_id:
                  description: 'ID data Supervision yang akan dibuatkan surat tugas.'
                  type: integer
                  example: 1
      responses:
        '201':
          description: 'Surat tugas pembimbing berhasil dibuat'
        '404':
          description: 'Data pembimbing tidak ditemukan'
          
  '/surat-tugas/{id}':
    get:
      tags:
        - 'Surat Tugas'
      summary: 'Mengunduh file surat tugas.'
      description: 'Mengunduh file surat tugas yang tersimpan di storage lokal berdasarkan ID Surat Tugas.'
      operationId: downloadSuratTugas
      parameters:
        - name: id
          in: path
          description: 'ID SuratTugas yang akan diunduh.'
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: 'Berhasil mengunduh file.'
          content:
            application/octet-stream: {}
        '404':
          description: 'File surat tugas tidak ditemukan'
    delete:
      tags:
        - 'Surat Tugas'
      summary: 'Menghapus surat tugas dan file terkait.'
      description: 'Menghapus record SuratTugas dari database dan file dari storage.'
      operationId: deleteSuratTugas
      parameters:
        - name: id
          in: path
          description: 'ID SuratTugas yang akan dihapus.'
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: 'Surat tugas pembimbing berhasil dihapus'
        '404':
          description: 'Surat tugas pembimbing tidak ditemukan'
          
  '/notifikasi/{supervisionId}':
    post:
      tags:
        - Pembimbingan
      summary: 'Mengirim notifikasi penunjukan pembimbing.'
      description: 'Mensimulasikan pengiriman notifikasi/email ke mahasiswa dan dosen terkait penunjukan.'
      operationId: kirimNotifikasi
      parameters:
        - name: supervisionId
          in: path
          description: 'ID data Supervision yang akan dikirimkan notifikasi.'
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: 'Notifikasi berhasil dikirim ke mahasiswa dan dosen'
        '404':
          description: 'Data pembimbing tidak ditemukan'
          
  '/pembimbing/{id}':
    put:
      tags:
        - Pembimbingan
      summary: 'Memperbarui dosen pembimbing dan/atau judul tugas.'
      description: 'Memperbarui data pembimbing (Supervision), menghapus surat tugas lama, dan membuat yang baru secara otomatis.'
      operationId: updatePembimbing
      parameters:
        - name: id
          in: path
          description: 'ID data Supervision yang akan diperbarui.'
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - lecturer_id
              properties:
                lecturer_id:
                  description: 'ID Dosen pembimbing yang baru.'
                  type: integer
                  example: 15
                judul:
                  description: 'Judul tugas yang diperbarui (optional).'
                  type: string
                  example: 'Perancangan Ulang Sistem Informasi'
      responses:
        '200':
          description: 'Dosen pembimbing berhasil diperbarui dan surat tugas baru dibuat'
        '404':
          description: 'Data pembimbing tidak ditemukan'
          
  /api/validasi-logbook:
    get:
      tags:
        - 'Validasi Logbook'
      summary: 'Menampilkan semua data validasi'
      operationId: 4c8515eb77a36011690dee4d58169c52
      responses:
        '200':
          description: Success
    post:
      tags:
        - 'Validasi Logbook'
      summary: 'Membuat validasi baru'
      operationId: b1b9ef6dedce63b7e19c1512509793ec
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - logbook_kp_id
                - lecturer_id
                - status_validasi
              properties:
                logbook_kp_id:
                  type: integer
                  example: 1
                lecturer_id:
                  type: integer
                  example: 12
                status_validasi:
                  type: string
                  example: Disetujui
                catatan_pembimbing:
                  type: string
                  example: 'Bagus, lanjutkan.'
      responses:
        '201':
          description: 'Validasi berhasil dibuat'
        '422':
          description: 'Validasi gagal'
          
  '/api/validasi-logbook/{id}':
    get:
      tags:
        - 'Validasi Logbook'
      summary: 'Menampilkan detail validasi berdasarkan ID'
      operationId: d7ad00f942cb049445b101ac08004a3d
      parameters:
        - name: id
          in: path
          description: 'ID validasi'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '404':
          description: 'Not Found'
    put:
      tags:
        - 'Validasi Logbook'
      summary: 'Memperbarui validasi logbook'
      operationId: cff55a6de9c76da6dfe493e5e3ca8580
      parameters:
        - name: id
          in: path
          description: 'ID validasi yang akan diperbarui'
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status_validasi:
                  type: string
                  example: Revisi
                catatan_pembimbing:
                  type: string
                  example: 'Tolong revisi bagian hasil.'
      responses:
        '200':
          description: Updated
        '404':
          description: 'Not Found'
    delete:
      tags:
        - 'Validasi Logbook'
      summary: 'Menghapus validasi logbook'
      operationId: d375560dfda909b7a5c3db088fd681d1
      parameters:
        - name: id
          in: path
          description: 'ID validasi yang akan dihapus.'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Deleted
        '404':
          description: 'Not Found'
          
tags:
  - name: 'Validasi Logbook'
    description: 'API untuk melakukan validasi logbook mahasiswa'
  - name: 'Pembimbingan'
    description: 'Operasi terkait penentuan, pembaruan dosen pembimbing, dan notifikasi.'
  - name: 'Surat Tugas'
    description: 'Operasi terkait pembuatan, pengunduhan, dan penghapusan dokumen Surat Tugas.'