openapi: 3.0.0
info:
  title: 'API Layanan KP'
  description: 'Dokumentasi API Validasi Logbook Mahasiswa'
  contact:
    email: admin@unand.ac.id
  version: 1.0.0
paths:
  /logbook:
    post:
      tags:
        - 'Logbook (Siswa)'
      summary: 'Siswa mengunggah Logbook kegiatan mingguan (termasuk file).'
      description: 'Mengunggah Logbook baru. Mendukung pengiriman file kegiatan opsional.'
      operationId: storeLogbook
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              required:
                - student_id
                - minggu_ke
                - tanggal_mulai
                - deskripsi_kegiatan
              properties:
                student_id:
                  description: 'ID Siswa'
                  type: integer
                  example: 5
                minggu_ke:
                  description: 'Minggu ke- KP (unik per siswa)'
                  type: integer
                  example: 3
                tanggal_mulai:
                  description: 'Tanggal mulai minggu kegiatan (YYYY-MM-DD)'
                  type: string
                  format: date
                  example: '2025-01-20'
                deskripsi_kegiatan:
                  type: string
                  example: 'Melakukan instalasi dan konfigurasi server.'
                file_kegiatan:
                  description: 'File pendukung (maks 2MB, pdf, doc, docx, jpg, jpeg, png).'
                  type: string
                  format: binary
                  nullable: true
              type: object
      responses:
        201:
          description: 'Logbook berhasil dibuat.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogbookKP'
        422:
          description: 'Kesalahan Validasi.'
  '/logbook/{studentId}':
    get:
      tags:
        - 'Logbook (Siswa)'
      summary: 'Mengambil semua Logbook (beserta validasinya) untuk seorang siswa.'
      description: 'Menampilkan daftar semua Logbook siswa untuk pelacakan kemajuan KP.'
      operationId: indexLogbook
      parameters:
        -
          name: studentId
          in: path
          description: 'ID Siswa'
          required: true
          schema:
            type: integer
            format: int64
            example: 5
      responses:
        200:
          description: 'Daftar Logbook siswa.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LogbookKPWithValidation'
  '/logbook/detail/{logbookId}':
    get:
      tags:
        - 'Logbook (Siswa)'
      summary: 'Menampilkan detail satu Logbook.'
      description: 'Mendapatkan detail Logbook beserta data validasinya.'
      operationId: showLogbook
      parameters:
        -
          name: logbookId
          in: path
          description: 'ID Logbook'
          required: true
          schema:
            type: integer
            format: int64
            example: 10
      responses:
        200:
          description: 'Detail Logbook.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogbookKPWithValidation'
        404:
          description: 'Logbook tidak ditemukan.'
  '/logbook/{logbookId}':
    put:
      tags:
        - 'Logbook (Siswa)'
      summary: 'Siswa mengupdate Logbook yang belum divalidasi'
      description: "Memperbarui data Logbook KP. Pembaruan hanya dapat dilakukan jika status Logbook masih 'Pending'. File kegiatan dapat diganti (opsional)."
      operationId: updateLogbook
      parameters:
        -
          name: logbookId
          in: path
          description: 'ID Logbook'
          required: true
          schema:
            type: integer
            example: 10
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              required:
                - minggu_ke
                - tanggal_mulai
                - deskripsi_kegiatan
              properties:
                minggu_ke:
                  description: 'Minggu ke kegiatan KP'
                  type: integer
                  example: 4
                tanggal_mulai:
                  type: string
                  format: date
                  example: '2025-01-27'
                deskripsi_kegiatan:
                  type: string
                  example: 'Melakukan coding modul A.'
                file_kegiatan:
                  description: 'File laporan/kegiatan (pdf, doc, docx, jpg, png) — opsional'
                  type: string
                  format: binary
              type: object
      responses:
        200:
          description: 'Logbook berhasil diperbarui'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogbookKP'
        403:
          description: 'Logbook sudah divalidasi dan tidak dapat diubah'
        404:
          description: 'Logbook tidak ditemukan'
        422:
          description: 'Kesalahan validasi'
    delete:
      tags:
        - 'Logbook (Siswa)'
      summary: 'Siswa menghapus Logbook yang belum divalidasi.'
      description: "Menghapus data Logbook. Penghapusan diblokir jika status Logbook bukan 'Pending'."
      operationId: destroyLogbook
      parameters:
        -
          name: logbookId
          in: path
          description: 'ID Logbook'
          required: true
          schema:
            type: integer
            format: int64
            example: 10
      responses:
        200:
          description: 'Logbook berhasil dihapus.'
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: 'Logbook berhasil dihapus.'
                type: object
        403:
          description: 'Logbook sudah divalidasi dan tidak dapat dihapus.'
        404:
          description: 'Logbook tidak ditemukan.'
  /pembimbing:
    post:
      tags:
        - Pembimbingan
      summary: 'Menentukan dosen pembimbing baru.'
      description: 'Mencatat penunjukan dosen pembimbing beserta judul tugas untuk mahasiswa.'
      operationId: tentukanPembimbing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - student_id
                - lecturer_id
                - judul
              properties:
                student_id:
                  description: 'ID Mahasiswa yang akan dibimbing.'
                  type: integer
                  example: 1
                lecturer_id:
                  description: 'ID Dosen pembimbing.'
                  type: integer
                  example: 12
                judul:
                  description: 'Judul tugas yang akan dibimbing.'
                  type: string
                  example: 'Rancangan Sistem Informasi Akademik'
              type: object
      responses:
        201:
          description: 'Dosen pembimbing berhasil ditentukan'
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: 'Dosen pembimbing berhasil ditentukan'
                type: object
        422:
          description: 'Validasi gagal'
  /surat-tugas:
    post:
      tags:
        - 'Surat Tugas'
      summary: 'Membuat dan menyimpan surat tugas pembimbing.'
      description: 'Membuat file surat tugas (simulasi .txt) dan mencatatnya ke database.'
      operationId: buatSuratTugas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - supervision_id
              properties:
                supervision_id:
                  description: 'ID data Supervision yang akan dibuatkan surat tugas.'
                  type: integer
                  example: 1
              type: object
      responses:
        201:
          description: 'Surat tugas pembimbing berhasil dibuat'
        404:
          description: 'Data pembimbing tidak ditemukan'
  '/surat-tugas/{id}':
    get:
      tags:
        - 'Surat Tugas'
      summary: 'Mengunduh file surat tugas.'
      description: 'Mengunduh file surat tugas yang tersimpan di storage lokal berdasarkan ID Surat Tugas.'
      operationId: downloadSuratTugas
      parameters:
        -
          name: id
          in: path
          description: 'ID SuratTugas yang akan diunduh.'
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        200:
          description: 'Berhasil mengunduh file.'
          content:
            application/octet-stream: []
        404:
          description: 'File surat tugas tidak ditemukan'
    delete:
      tags:
        - 'Surat Tugas'
      summary: 'Menghapus surat tugas dan file terkait.'
      description: 'Menghapus record SuratTugas dari database dan file dari storage.'
      operationId: deleteSuratTugas
      parameters:
        -
          name: id
          in: path
          description: 'ID SuratTugas yang akan dihapus.'
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        200:
          description: 'Surat tugas pembimbing berhasil dihapus'
        404:
          description: 'Surat tugas pembimbing tidak ditemukan'
  '/notifikasi/{supervisionId}':
    post:
      tags:
        - Pembimbingan
      summary: 'Mengirim notifikasi penunjukan pembimbing.'
      description: 'Mensimulasikan pengiriman notifikasi/email ke mahasiswa dan dosen terkait penunjukan.'
      operationId: kirimNotifikasi
      parameters:
        -
          name: supervisionId
          in: path
          description: 'ID data Supervision yang akan dikirimkan notifikasi.'
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        200:
          description: 'Notifikasi berhasil dikirim ke mahasiswa dan dosen'
        404:
          description: 'Data pembimbing tidak ditemukan'
  '/pembimbing/{id}':
    put:
      tags:
        - Pembimbingan
      summary: 'Memperbarui dosen pembimbing dan/atau judul tugas.'
      description: 'Memperbarui data pembimbing (Supervision), menghapus surat tugas lama, dan membuat yang baru secara otomatis.'
      operationId: updatePembimbing
      parameters:
        -
          name: id
          in: path
          description: 'ID data Supervision yang akan diperbarui.'
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - lecturer_id
              properties:
                lecturer_id:
                  description: 'ID Dosen pembimbing yang baru.'
                  type: integer
                  example: 15
                judul:
                  description: 'Judul tugas yang diperbarui (optional).'
                  type: string
                  example: 'Perancangan Ulang Sistem Informasi'
              type: object
      responses:
        200:
          description: 'Dosen pembimbing berhasil diperbarui dan surat tugas baru dibuat'
        404:
          description: 'Data pembimbing tidak ditemukan'
  /api/validasi:
    get:
      tags:
        - 'Validasi Logbook'
      summary: 'Menampilkan semua data validasi'
      operationId: 4c8515eb77a36011690dee4d58169c52
      responses:
        200:
          description: Success
    post:
      tags:
        - 'Validasi Logbook'
      summary: 'Membuat validasi baru'
      operationId: b1b9ef6dedce63b7e19c1512509793ec
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - logbook_kp_id
                - lecturer_id
                - status_validasi
              properties:
                logbook_kp_id:
                  type: integer
                  example: 1
                lecturer_id:
                  type: integer
                  example: 12
                status_validasi:
                  type: string
                  example: Disetujui
                catatan_pembimbing:
                  type: string
                  example: 'Bagus, lanjutkan.'
              type: object
      responses:
        201:
          description: 'Validasi berhasil dibuat'
        422:
          description: 'Validasi gagal'
  '/api/validasi/{id}':
    get:
      tags:
        - 'Validasi Logbook'
      summary: 'Menampilkan detail validasi berdasarkan ID'
      operationId: d7ad00f942cb049445b101ac08004a3d
      parameters:
        -
          name: id
          in: path
          description: 'ID validasi'
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Success
        404:
          description: 'Not Found'
    put:
      tags:
        - 'Validasi Logbook'
      summary: 'Memperbarui validasi logbook'
      operationId: cff55a6de9c76da6dfe493e5e3ca8580
      parameters:
        -
          name: id
          in: path
          description: 'ID validasi yang akan diperbarui'
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              properties:
                status_validasi:
                  type: string
                  example: Revisi
                catatan_pembimbing:
                  type: string
                  example: 'Tolong revisi bagian hasil.'
              type: object
      responses:
        200:
          description: Updated
        404:
          description: 'Not Found'
    delete:
      tags:
        - 'Validasi Logbook'
      summary: 'Menghapus validasi logbook'
      operationId: d375560dfda909b7a5c3db088fd681d1
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Deleted
        404:
          description: 'Not Found'
components:
  schemas:
    LogbookKP:
      title: LogbookKP
      description: 'Model data Logbook Kerja Praktik.'
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        student_id:
          type: integer
          example: 5
        minggu_ke:
          description: 'Minggu ke- KP (unik per siswa).'
          type: integer
          example: 3
        tanggal_mulai:
          type: string
          format: date
          example: '2025-01-20'
        deskripsi_kegiatan:
          type: string
          example: 'Melakukan instalasi dan konfigurasi server.'
        file_kegiatan:
          description: 'Path file kegiatan.'
          type: string
          example: logbook_files/abc.pdf
          nullable: true
        status:
          type: string
          default: Pending
          enum:
            - Pending
            - Validated
            - Rejected
          readOnly: true
      type: object
    ValidasiLogbook:
      title: ValidasiLogbook
      description: 'Model data Validasi Logbook oleh Dosen/Validator.'
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        status:
          type: string
          enum:
            - Validated
            - Rejected
          example: Validated
        catatan_validator:
          type: string
          example: 'Laporan mingguan sudah baik.'
          nullable: true
      type: object
    LogbookKPWithValidation:
      allOf:
        -
          $ref: '#/components/schemas/LogbookKP'
        -
          properties:
            validasi:
              oneOf:
                -
                  $ref: '#/components/schemas/ValidasiLogbook'
              nullable: true
          type: object
tags:
  -
    name: 'Logbook (Siswa)'
    description: 'Operasi CRUD dan Tracking Logbook kegiatan KP oleh Mahasiswa.'
  -
    name: Pembimbingan
    description: 'Operasi terkait penentuan, pembaruan dosen pembimbing, dan notifikasi.'
  -
    name: 'Surat Tugas'
    description: 'Operasi terkait pembuatan, pengunduhan, dan penghapusan dokumen Surat Tugas.'
  -
    name: 'Validasi Logbook'
    description: 'API untuk melakukan validasi logbook mahasiswa'
