openapi: 3.0.3
info:
  title: Seminar KP API
  version: "1.0"
servers:
  - url: http://localhost:8000/api
paths:
  /seminars:
    get:
      summary: "List seminars"
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
    post:
      summary: Create seminar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, student_id]
              properties:
                title: { type: string }
                student_id: { type: integer }
                scheduled_at: { type: string, format: date-time }
                notes: { type: string }
                examiners:
                  type: array
                  items:
                    type: object
                    properties:
                      id: { type: integer }
                      role: { type: string, enum: [primary, secondary] }
      responses:
        '201':
          description: Created

  /seminars/{id}:
    get:
      summary: Show seminar
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        '200': { description: OK }
    put:
      summary: Update seminar
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title: { type: string }
                scheduled_at: { type: string, format: date-time }
                status: { type: string, enum: [pending, scheduled, done, cancelled] }
                notes: { type: string }
                examiners:
                  type: array
                  items:
                    type: object
                    properties:
                      id: { type: integer }
                      role: { type: string, enum: [primary, secondary] }
      responses:
        '200': { description: OK }
    delete:
      summary: Delete seminar
      responses:
        '200': { description: Deleted }

  /seminars/{id}/assign-examiners:
    post:
      summary: Assign examiners
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                examiners:
                  type: array
                  items:
                    type: object
                    properties:
                      id: { type: integer }
                      role: { type: string, enum: [primary, secondary] }
      responses:
        '200': { description: OK }

  /seminars/{id}/notify:
    post:
      summary: Send custom notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [message]
              properties:
                message: { type: string }
      responses:
        '200': { description: Notified }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
