<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PembimbingController;
use App\Http\Controllers\PendaftaranKPController;
use App\Http\Controllers\InformasiKPController;
use App\Http\Controllers\SyaratKPController;
use App\Http\Controllers\JadwalKPController;
use App\Http\Controllers\TemplateDokumenController;
use App\Http\Controllers\ProsedurKPController;
use App\Http\Controllers\VerifikasiAdministrasiController;
use App\Http\Controllers\SuratPengantarKPController;

Route::post('/tentukan-pembimbing', [PembimbingController::class, 'tentukanPembimbing']);
Route::post('/buat-surat-tugas', [PembimbingController::class, 'buatSuratTugas']);
Route::get('/kirim-notifikasi/{id}', [PembimbingController::class, 'kirimNotifikasi']);
Route::post('/pendaftaran-kp', [PendaftaranKPController::class, 'daftar']);
Route::post('/pendaftaran-kp/{id}/upload', [PendaftaranKPController::class, 'uploadBerkas']);
Route::post('/pendaftaran-kp/{id}/validasi', [PendaftaranKPController::class, 'validasi']);
Route::get('/pendaftaran-kp/{id}', [PendaftaranKPController::class, 'detail']);
Route::get('/pendaftaran-kp', [PendaftaranKPController::class, 'daftarSemua']);
Route::put('/pendaftaran-kp/{id}', [PendaftaranKPController::class, 'update']);
Route::delete('/pendaftaran-kp/{id}', [PendaftaranKPController::class, 'delete']);
Route::post('/informasi-kp/syarat', [InformasiKPController::class, 'storeSyarat']);
Route::post('/informasi-kp/jadwal', [InformasiKPController::class, 'storeJadwal']);
Route::post('/informasi-kp/template', [InformasiKPController::class, 'storeTemplate']);
Route::post('/informasi-kp/prosedur', [InformasiKPController::class, 'storeProsedur']);
Route::post('/verifikasi-admin', [VerifikasiAdministrasiController::class, 'store']);
Route::get('/verifikasi-admin', [VerifikasiAdministrasiController::class, 'index']);
Route::get('/verifikasi-admin/{id}', [VerifikasiAdministrasiController::class, 'show']);
Route::post('/verifikasi-admin/{id}/cek-kelengkapan', [VerifikasiAdministrasiController::class, 'cekKelengkapan']);
Route::post('/verifikasi-admin/{id}/setujui', [VerifikasiAdministrasiController::class, 'setujui']);
Route::post('/verifikasi-admin/{id}/tolak', [VerifikasiAdministrasiController::class, 'tolak']);
Route::get('/verifikasi-admin/{id}/status-mahasiswa', [VerifikasiAdministrasiController::class, 'getStatusMahasiswa']);
Route::post('/surat-pengantar', [SuratPengantarKPController::class, 'store']);
Route::get('/surat-pengantar', [SuratPengantarKPController::class, 'index']);
Route::get('/surat-pengantar/{id}', [SuratPengantarKPController::class, 'show']);
Route::post('/surat-pengantar/{id}/buat-pdf', [SuratPengantarKPController::class, 'buatPDF']);
Route::post('/surat-pengantar/{id}/tandatangani', [SuratPengantarKPController::class, 'tandatangani']);
Route::post('/surat-pengantar/{id}/tolak', [SuratPengantarKPController::class, 'tolak']);
Route::get('/surat-pengantar/{id}/download', [SuratPengantarKPController::class, 'download']);
Route::get('/surat-pengantar/{id}/status', [SuratPengantarKPController::class, 'getStatus']);